---
title: "Preprocessing"
author: "Nicole"
date: "27/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install packages and load data 
```{r}
# packages
library(pacman)
p_load(tidyverse,gdata,metafor,lmerTest)

# data (from shinyapps/sitedata)
scz <- read_csv("rawdata/schizophrenia_parola_2020.csv")
asd <- read_csv("rawdata/asd_fusaroli_2017.csv")
lhd <- read_csv("rawdata/lhd_weed_2020.csv")
rhd <- read_csv("rawdata/rhd_weed_2020.csv")

```

Merging the data
```{r}
# merging
merge <- gdata::combine(scz, asd, lhd, rhd) 

# re-oder columns and rename
data <- merge[,c(65,1:64)] %>%
  rename("disorder" = source) %>%
  mutate(same_sample =  paste0(same_sample, "_", disorder),
         mean_age_1_years = ifelse(disorder == "asd", mean_age_1/12, mean_age_1),
         mean_age_2_years = ifelse(disorder == "asd", mean_age_2/12, mean_age_2))

```

Add some columns
```{r}
# remove empty column
data$X1 <- NULL 

# study disorder: because there are some studies which investigated 2 disorder (esp. rhd/lhd)
data$study_disorder <- paste(data$study_ID, data$disorder, sep = "_")

# grouped factors for disorder and expt-unique 
data$dis_task <- paste(data$disorder, data$task_type, sep = "_")
data$dis_lang <- paste(data$disorder, data$native_language, sep = "_")
data$expt_unique_dis <- paste(data$expt_unique, data$disorder, sep = "_")

```

Save file
```{r}

# change name when you save it again, finaldata_18_11_2020.csv is the one we use for the analysis.
#write.csv(data, "data/finaldata_18_11_2020.csv") 
predata <- read_csv("data/finaldata_18_11_2020.csv") 
```

### SUMMARY STATISTICS FOR PAPER ###

First look at the missing data: we have already taken out all of the NA's in x_1, x_2, SD_1 and SD_2
Summary statistics: then count the participants and recordings by diagnosis, report their gender, age
```{r}
# number of papers
# total
length(unique(predata$short_cite))
# by disorder
n_papers <- predata %>% group_by(short_cite) %>% #could also be grouped by study_ID = the same
  summarise(dis = list(unique(as.character(disorder))), .groups = "drop_last") %>%
  group_by(dis) %>%
  summarise(n = n())

# unique experiments/studies 
# total
length(unique(predata$expt_unique))
# by disorder
n_studies <- predata %>% group_by(expt_unique) %>% 
  summarise(dis = list(unique(as.character(disorder))), .groups = "drop_last") %>%
  group_by(dis) %>%
  summarise(n = n())

# number of studies and unique experiments
# NOT USED!!!!!
study_summary <- predata %>% 
  group_by(disorder) %>% 
  summarise(n_studies = n_distinct(study_ID),
            n_unique_expt = n_distinct(expt_unique), 
            n_samples = n_distinct(same_sample),
            n_row = n(),
            .groups = "drop_last")
study_summary

# languages
levels(as.factor(predata$native_language))

# test <- data %>% group_by(disorder, short_cite) %>%
#   summarise(n = n()) %>%
#   group_by(short_cite) %>%
#   summarise(n = n(), dis = list(disorder), dis2 = disorder)

#############

#  participant summary statistics
# first make a data set that only has one row for unique samples
participant_sample <- predata %>% group_by(same_sample, disorder) %>%
  summarise(n_1 = as.integer(max(n_1)),
            n_2 = as.integer(max(n_2)),
            female_n_1 = as.integer(mean(n_1_F, na.rm = T)),
            male_n_1 = as.integer(mean(n_1_M, na.rm = T)),
            female_n_2 = as.integer(mean(n_2_F, na.rm = T)),
            male_n_2 = as.integer(mean(n_2_M, na.rm = T))) 
participant_sample$n_2[participant_sample$disorder == "lhd"] <- NA
#total
sum(participant_sample$n_1, na.rm = T) + sum(participant_sample$n_2, na.rm = T)  
# by disorder
participants <- participant_sample %>%
  group_by(disorder) %>%
  summarise(n_patient = sum(n_1),
            n_control = sum(n_2, na.rm = T),
            total = sum(n_1) + sum(n_2, na.rm = T),
            female_n_1 = sum(female_n_1, na.rm = T),
            male_n_1 = sum(male_n_1, na.rm = T),
            female_n_2 = sum(female_n_2, na.rm = T),
            male_n_2 = sum(male_n_2, na.rm = T),
            .groups = "drop_last")
participants

# Checking whether there are different values within the same samples, or whether we can just take a mean of the group.
predata %>% group_by(same_sample) %>% summarise(n = n()) %>% nrow() # 79
predata %>% group_by(same_sample, n_1) %>% summarise(n = n()) %>% nrow() # 83 --> max
predata %>% group_by(same_sample, n_2) %>% summarise(n = n()) %>% nrow() # 83
predata %>% group_by(same_sample, n_1_F) %>% summarise(n = n()) %>% nrow() # 79 --> mean
predata %>% group_by(same_sample, n_1_M) %>% summarise(n = n()) %>% nrow() # 79
predata %>% group_by(same_sample, n_2_F) %>% summarise(n = n()) %>% nrow() # 79
predata %>% group_by(same_sample, n_2_M) %>% summarise(n = n()) %>% nrow() # 79
predata %>% group_by(same_sample) %>% summarise(n = n()) %>% nrow() # 79
predata %>% group_by(same_sample) %>% summarise(n = n()) %>% nrow() # 79


# Sample info - age
d_df <- distinct(predata, same_sample, .keep_all = T)

# then summarize
sample_summary <- d_df %>%
  group_by(disorder) %>%
  summarise(m_age_1 = mean(mean_age_1_years, na.rm = T),
            m_age_2 = mean(mean_age_2_years, na.rm = T),
            sd_age_1 = sd(mean_age_1_years, na.rm = T),
            sd_age_2 = sd(mean_age_2_years, na.rm = T),
            min_age_1 = min(mean_age_1_years, na.rm = T),
            min_age_2 = min(mean_age_2_years, na.rm = T),
            max_age_1 = max(mean_age_1_years, na.rm = T),
            max_age_2 = max(mean_age_2_years, na.rm = T),
            langugaes = list(unique(native_language)),
            .groups = "drop_last")

view(sample_summary)
```

